-- ============================================================================
--  QUIZ BÍBLICO · seed_books.sql  (GERADO — não edite à mão)
--  Gerado por: node scripts/build-seed-sql.mjs
--  Fonte canônica: backend/src/db/seeds/*.js
--  150 perguntas (50 por livro: 15 fáceis · 20 médias · 15 difíceis)
--  + 21 conquistas (7 por livro)
-- ----------------------------------------------------------------------------
--  Idempotente: pode ser executado mais de uma vez sem duplicar dados.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- LIVROS
-- ---------------------------------------------------------------------------
insert into public.books (id, name, short_name, chapters, testament, icon, color, order_index, description, active) values
  ('oseias', 'Oséias', 'OSÉIAS', 14, 'Antigo Testamento', '💧', '#38bdf8', 1, 'O profeta do amor fiel de Deus: casamento com Gômer, chamado ao arrependimento e promessas de restauração para Israel.', true),
  ('obadias', 'Obadias', 'OBADIAS', 1, 'Antigo Testamento', '🦅', '#fbbf24', 2, 'O menor livro do Antigo Testamento: a visão contra Edom, o Dia do Senhor e a certeza de que o reino será do Senhor.', true),
  ('jonas', 'Jonas', 'JONAS', 4, 'Antigo Testamento', '🐋', '#34d399', 3, 'O profeta fujão: a tempestade, o grande peixe, o arrependimento de Nínive e a lição da misericórdia de Deus.', true)
on conflict (id) do update set
  name = excluded.name, short_name = excluded.short_name, chapters = excluded.chapters,
  testament = excluded.testament, icon = excluded.icon, color = excluded.color,
  order_index = excluded.order_index, description = excluded.description, active = excluded.active;

-- ---------------------------------------------------------------------------
-- PERGUNTAS
-- ---------------------------------------------------------------------------
-- ===== OSÉIAS (50) =====
insert into public.questions
  (id, book_id, chapter, question, difficulty, option_a, option_b, option_c, option_d,
   correct_answer, explanation, hint, source_type, order_index)
values
('00000000-0000-4000-8000-010000000101', 'oseias', 1, 'Quem era o pai do profeta Oséias?', 'facil', 'Beeri', 'Joás', 'Diblaim', 'Bezalel', 'A', 'Oséias 1:1: "Palavra do Senhor, que veio a Oséias, filho de Beeri, nos dias de Uzias, Jotão, Acaz e Ezequias, reis de Judá, e nos dias de Jeroboão, filho de Joás, rei de Israel."', 'O nome aparece logo no primeiro versículo do livro.', 'texto_biblico', 1),
('00000000-0000-4000-8000-010000000102', 'oseias', 1, 'Qual era o nome da mulher de Oséias?', 'facil', 'Rute', 'Gômer', 'Noemia', 'Tamar', 'B', 'Oséias 1:3: Oséias "foi e tomou a Gômer, filha de Diblaim". O casamento do profeta com Gômer é o grande sinal vivo do livro: retrata o amor fiel de Deus por Israel, mesmo diante da infidelidade do povo.', 'Ela era filha de Diblaim.', 'texto_biblico', 2),
('00000000-0000-4000-8000-010000000103', 'oseias', 1, 'Qual foi o nome do primeiro filho de Oséias?', 'facil', 'Jezreel', 'Lo-Ami', 'Maer-Salal', 'Gersom', 'A', 'Oséias 1:4: "Põe-lhe o nome de Jezreel, porque, daqui a pouco, castigarei o sangue de Jezreel sobre a casa de Jeú." Jezreel significa "Deus semeia/espalha" e lembra o vale onde Jeú derramou sangue (2 Reis 9–10).', 'É também o nome de um vale famoso em Israel.', 'texto_biblico', 3),
('00000000-0000-4000-8000-010000000104', 'oseias', 1, 'O que significa o nome "Lo-Ami", dado ao terceiro filho de Oséias?', 'facil', 'Deus conosco', 'Filho da promessa', 'Vocês não são meu povo', 'Misericórdia encontrada', 'C', 'Oséias 1:9: "Põe-lhe o nome de Lo-Ami, porque vós não sois meu povo, nem eu serei vosso Deus." O próprio texto traduz o nome. Mais tarde, em 2:23, Deus reverte a sentença: dirá a Lo-Ami "Tu és meu povo".', 'O próprio versículo traduz o nome logo em seguida.', 'texto_biblico', 4),
('00000000-0000-4000-8000-010000000105', 'oseias', 6, 'Complete a frase de Oséias 6:6: "Misericórdia quero, e não ___".', 'facil', 'jejum', 'oração', 'sacrifício', 'oferta de manjares', 'C', 'Oséias 6:6: "Porque misericórdia quero, e não sacrifício, e o conhecimento de Deus, mais do que holocaustos." Jesus citou esse versículo duas vezes (Mateus 9:13 e 12:7) para mostrar que Deus valoriza o coração fiel acima do ritual vazio.', 'Jesus citou essa frase ao falar com os fariseus.', 'texto_biblico', 5),
('00000000-0000-4000-8000-010000000106', 'oseias', 4, 'Complete Oséias 4:6: "O meu povo está sendo destruído porque lhe falta ___".', 'facil', 'o conhecimento', 'a força', 'o ouro', 'um rei', 'A', 'Oséias 4:6: "O meu povo está sendo destruído, porque lhe falta o conhecimento. Porque tu rejeitaste o conhecimento, também eu te rejeitarei." A ignorância da Palavra de Deus é apontada como causa da ruína de Israel.', 'É algo que se aprende ouvindo a Palavra de Deus.', 'texto_biblico', 6),
('00000000-0000-4000-8000-010000000107', 'oseias', 8, 'Complete o provérbio de Oséias 8:7: "Semeiam ventos e segarão ___".', 'facil', 'flores', 'tormentas', 'espinhos', 'uvas bravas', 'B', 'Oséias 8:7: "Porque semeiam o vento e segarão a tormenta." O provérbio ensina a lei da semeadura: alianças erradas e idolatria trariam uma colheita de destruição muito maior do que o plantio.', 'É uma tempestade bem maior do que uma brisa.', 'texto_biblico', 7),
('00000000-0000-4000-8000-010000000108', 'oseias', 14, 'Quantos capítulos tem o livro de Oséias?', 'facil', '10', '12', '14', '16', 'C', 'O livro de Oséias possui 14 capítulos. Os capítulos 1 a 3 usam o casamento do profeta como parábola viva; os capítulos 4 a 13 trazem denúncias e juízos; o capítulo 14 encerra com o chamado ao arrependimento e promessas de restauração.', 'É o primeiro dos Profetas Menores e um dos mais longos entre eles.', 'texto_biblico', 8),
('00000000-0000-4000-8000-010000000109', 'oseias', 11, 'Complete Oséias 11:1: "Quando Israel era menino, eu o amei, e do ___ chamei o meu filho".', 'facil', 'deserto', 'Egito', 'cativeiro da Babilônia', 'monte Sinai', 'B', 'Oséias 11:1: "Quando Israel era menino, eu o amei; e do Egito chamei o meu filho." O versículo recorda o Êxodo e foi aplicado por Mateus 2:15 à volta do menino Jesus do Egito.', 'Foi de lá que Deus tirou o povo com mão forte no Êxodo.', 'texto_biblico', 9),
('00000000-0000-4000-8000-010000000110', 'oseias', 2, 'Em Oséias 2, Deus promete se desposar (casar) com Israel em quê?', 'facil', 'Em riquezas e palácios', 'Em guerras e conquistas', 'Em silêncio e distância', 'Em fidelidade', 'D', 'Oséias 2:19-20: "Desposar-te-ei comigo em justiça, em juízo, em benignidade e em misericórdias; desposar-te-ei comigo em fidelidade, e conhecerás ao Senhor." O casamento restaurado é a imagem da nova aliança.', 'É o oposto da infidelidade que marcou o povo.', 'texto_biblico', 10),
('00000000-0000-4000-8000-010000000111', 'oseias', 14, 'Qual é o grande chamado do último capítulo de Oséias?', 'facil', 'Fugir para o Egito', 'Voltar para o Senhor', 'Reconstruir os muros', 'Coroar um novo rei', 'B', 'Oséias 14:1-2: "Volta, ó Israel, para o Senhor, teu Deus... Tomai convosco palavras e voltai-vos ao Senhor." Depois de todas as denúncias, o livro termina com um convite ao arrependimento e promessas de cura e amor (14:4).', 'Começa com "Volta, ó Israel…".', 'texto_biblico', 11),
('00000000-0000-4000-8000-010000000112', 'oseias', 7, 'Em Oséias 7:8, Efraim é comparado a um bolo que…', 'facil', 'cresceu demais e transbordou', 'não foi virado', 'foi feito sem fermento', 'alimentou uma multidão', 'B', 'Oséias 7:8: "Efraim se mistura com os povos; Efraim é um bolo que não foi virado." Assado só de um lado, o bolo queima por baixo e fica cru por cima: retrato de um povo pela metade, misturado com as nações e inútil para Deus.', 'O problema é que ele foi assado de um lado só.', 'texto_biblico', 12),
('00000000-0000-4000-8000-010000000113', 'oseias', 7, 'Em Oséias 7:11, Efraim é comparado a qual ave?', 'facil', 'Águia', 'Corvo', 'Pomba', 'Andorinha', 'C', 'Oséias 7:11: "Efraim é como uma pomba enganada, sem entendimento; invocam o Egito, vão para a Assíria." A pomba ingênua voa de um lado para outro: Israel buscava socorro ora no Egito, ora na Assíria, em vez de confiar em Deus.', 'É uma ave conhecida por ser mansa e fácil de enganar.', 'texto_biblico', 13),
('00000000-0000-4000-8000-010000000114', 'oseias', 13, 'Complete Oséias 13:14: "Ó morte, onde estão as tuas ___?"', 'facil', 'pragas', 'correntes', 'armadilhas', 'trevas', 'A', 'Oséias 13:14: "Ó morte, onde estão as tuas pragas? Ó inferno, onde está a tua destruição?" Paulo ecoa essa vitória sobre a morte em 1 Coríntios 15:55: "Onde está, ó morte, a tua vitória?"', 'Paulo cita esse triunfo sobre a morte em 1 Coríntios 15.', 'texto_biblico', 14),
('00000000-0000-4000-8000-010000000115', 'oseias', 1, 'Oséias profetizou principalmente para qual reino?', 'facil', 'O reino do Sul (Judá)', 'O reino do Norte (Israel/Efraim)', 'O reino de Edom', 'O império da Babilônia', 'B', 'Embora cite reis de Judá na introdução (1:1), Oséias dirigiu sua mensagem sobretudo ao reino do Norte, chamado no livro de "Israel", "Efraim" e "Samaria". Ele viveu nos últimos dias antes da queda de Samaria diante da Assíria (722 a.C.).', 'No livro, esse reino é chamado muitas vezes de "Efraim".', 'texto_biblico', 15),
('00000000-0000-4000-8000-010000000201', 'oseias', 1, 'Qual foi o nome da filha de Oséias?', 'medio', 'Lo-Ruama', 'Ruama', 'Jezreel', 'Ami', 'A', 'Oséias 1:6: Gômer "concebeu e deu à luz uma filha. Disse-lhe o Senhor: Põe-lhe o nome de Lo-Ruama, porque eu não tornarei a compadecer-me da casa de Israel." Lo-Ruama significa "não amada / não alcançou misericórdia".', 'O nome começa com "Lo-", que em hebraico nega a palavra seguinte.', 'texto_biblico', 16),
('00000000-0000-4000-8000-010000000202', 'oseias', 1, 'Qual rei de Israel é citado em Oséias 1:1?', 'medio', 'Acabe, filho de Onri', 'Jeú, filho de Josafá', 'Jeroboão, filho de Joás', 'Peca, filho de Remalias', 'C', 'Oséias 1:1 situa o ministério do profeta "nos dias de Jeroboão, filho de Joás, rei de Israel" (Jeroboão II). Foi um tempo de prosperidade material e decadência espiritual no reino do Norte, como também mostra o profeta Amós, seu contemporâneo.', 'É o rei do longo reinado próspero do século VIII a.C., filho de Joás.', 'texto_biblico', 17),
('00000000-0000-4000-8000-010000000203', 'oseias', 2, 'Segundo Oséias 2:15, o vale de Acor se tornaria o quê?', 'medio', 'Um campo de batalha', 'Uma porta de esperança', 'Um deserto sem água', 'Um lugar de exílio', 'B', 'Oséias 2:15: "Dar-lhe-ei as suas vinhas dali e o vale de Acor por porta de esperança." O vale de Acor, marcado pelo pecado de Acã (Josué 7), seria transformado em símbolo de novo começo.', 'O lugar da antiga derrota viraria símbolo de recomeço.', 'texto_biblico', 18),
('00000000-0000-4000-8000-010000000204', 'oseias', 3, 'O que Oséias pagou para readquirir Gômer, segundo Oséias 3:2?', 'medio', 'Trinta siclos de prata', 'Sete cordeiros', 'Quinze siclos de prata e cevada', 'Um par de bois', 'C', 'Oséias 3:2: "Comprei-a, pois, para mim por quinze peças de prata, e um ômer e meio de cevada." O preço humilde pago pelo profeta ilustra o resgate amoroso com que Deus tornaria a buscar Israel.', 'Foram quinze peças de prata mais uma medida de cereal.', 'texto_biblico', 19),
('00000000-0000-4000-8000-010000000205', 'oseias', 3, 'Segundo Oséias 3:4, os filhos de Israel ficariam muitos dias sem o quê?', 'medio', 'Sem pão e sem água', 'Sem rei e sem príncipe', 'Sem filhos e sem filhas', 'Sem portas e sem muros', 'B', 'Oséias 3:4: "Porque os filhos de Israel ficarão por muitos dias sem rei, sem príncipe, sem sacrifício, sem coluna, sem éfode e sem terafins." Depois, "tornarão e buscarão ao Senhor... e a Davi, seu rei" (3:5).', 'A lista começa com duas autoridades: uma maior e uma menor.', 'texto_biblico', 20),
('00000000-0000-4000-8000-010000000206', 'oseias', 4, 'Complete Oséias 4:17: "Efraim está entregue aos ___; deixa-o".', 'medio', 'assírios', 'ídolos', 'mercadores', 'leões', 'B', 'Oséias 4:17: "Efraim está entregue aos ídolos; deixa-o." É um dos versículos mais solenes do livro: Deus entrega o povo obstinado às consequências da sua própria idolatria.', 'É aquilo que o povo adorava em vez de Deus.', 'texto_biblico', 21),
('00000000-0000-4000-8000-010000000207', 'oseias', 4, 'Em Oséias 4:15, Deus diz: "Não subais a ___".', 'medio', 'Jerusalém', 'Gilgal', 'Hebrom', 'Belém', 'B', 'Oséias 4:15: "Se tu, ó Israel, queres prostituir-te, ao menos não se faça culpado Judá; não venhais a Gilgal, e não subais a Bete-Áven." Gilgal e Bete-Áven (apelido de Betel, "casa da iniquidade") eram centros de culto idólatra.', 'É o mesmo lugar onde Israel acampou ao entrar em Canaã, agora corrompido.', 'texto_biblico', 22),
('00000000-0000-4000-8000-010000000208', 'oseias', 5, 'Complete Oséias 5:8: "Tocai a trombeta em Gibeá, a buzina em ___".', 'medio', 'Ramá', 'Jericó', 'Samaria', 'Dã', 'A', 'Oséias 5:8: "Tocai a trombeta em Gibeá, a buzina em Ramá; gritai em Bete-Áven: após ti, ó Benjamim!" O toque de alarme anuncia a invasão iminente sobre o reino.', 'É uma cidade de Benjamim, perto de Gibeá.', 'texto_biblico', 23),
('00000000-0000-4000-8000-010000000209', 'oseias', 5, 'Em Oséias 5:14, Deus diz que será para Efraim como um…', 'medio', 'cordeiro', 'leão', 'lobo', 'urso', 'B', 'Oséias 5:14: "Porque para Efraim serei como um leão e para a casa de Judá, como um leãozinho; eu, eu mesmo, despedaçarei e ir-me-ei embora." A imagem do leão mostra um juízo irresistível.', 'É o rei dos animais, símbolo de força irresistível.', 'texto_biblico', 24),
('00000000-0000-4000-8000-010000000210', 'oseias', 6, 'Complete Oséias 6:2: "Depois de dois dias, nos revigorará; ao terceiro dia, nos ___".', 'medio', 'julgará', 'espalhará', 'levantará', 'esconderá', 'C', 'Oséias 6:2: "Depois de dois dias, nos revigorará; ao terceiro dia, nos levantará, e viveremos diante dele." A restauração após o juízo é descrita como uma ressurreição — linguagem que o Novo Testamento cumpre em Cristo.', 'É o mesmo verbo usado para ressuscitar.', 'texto_biblico', 25),
('00000000-0000-4000-8000-010000000211', 'oseias', 6, 'Em Oséias 6:4, a bondade do povo é comparada à…', 'medio', 'nuvem da manhã', 'rocha do deserto', 'oliveira verde', 'estrela da alva', 'A', 'Oséias 6:4: "A vossa bondade é como a nuvem da manhã, como o orvalho da madrugada, que cedo passa." O arrependimento de Israel era superficial e passageiro, evaporando como a neblina.', 'É algo que some logo que o sol esquenta.', 'texto_biblico', 26),
('00000000-0000-4000-8000-010000000212', 'oseias', 8, 'Complete Oséias 8:6: "O bezerro de ___ será despedaçado".', 'medio', 'Dã', 'Betel', 'Samaria', 'Siquém', 'C', 'Oséias 8:5-6: "O teu bezerro, ó Samaria, é rejeitado... Porque o bezerro de Samaria será feito em pedaços." Os bezerros de ouro de Jeroboão I (Betel e Dã) são aqui associados à capital Samaria, centro da idolatria.', 'É a capital do reino do Norte.', 'texto_biblico', 27),
('00000000-0000-4000-8000-010000000213', 'oseias', 8, 'Segundo Oséias 8:12, como Israel tratou as grandezas da lei de Deus?', 'medio', 'Como tesouro precioso', 'Como coisa estranha', 'Como cântico novo', 'Como herança dos pais', 'B', 'Oséias 8:12: "Escrevi para ele as grandezas da minha lei, mas isso é tido como coisa estranha." Israel considerava a Palavra de Deus algo alheio, sem valor prático — retrato da irreverência do povo.', 'Eles agiam como se a lei fosse algo estrangeiro.', 'texto_biblico', 28),
('00000000-0000-4000-8000-010000000214', 'oseias', 9, 'Complete Oséias 9:10: "Como uvas no deserto achei a ___".', 'medio', 'Judá', 'Israel', 'Efraim somente', 'Benjamim', 'B', 'Oséias 9:10: "Como uvas no deserto achei a Israel, como figos temporãos na figueira nova vi a vossos pais." Deus lembra com ternura o início da história com o povo, antes da idolatria de Baal-Peor.', 'É o nome do povo inteiro escolhido por Deus.', 'texto_biblico', 29),
('00000000-0000-4000-8000-010000000215', 'oseias', 9, 'Segundo Oséias 9:15, onde se achava toda a maldade de Israel?', 'medio', 'Em Jerusalém', 'Em Gilgal', 'Em Tiro', 'Em Damasco', 'B', 'Oséias 9:15: "Toda a sua maldade se acha em Gilgal, porque ali passei a aborrecê-los." Gilgal, que fora lugar de bênção na conquista, tornara-se centro de culto falso; Amós também denunciou Gilgal (Amós 4:4; 5:5).', 'É o mesmo lugar citado em Oséias 4:15.', 'texto_biblico', 30),
('00000000-0000-4000-8000-010000000216', 'oseias', 10, 'Em Oséias 10:1, Israel é comparado a uma vide…', 'medio', 'seca', 'luxuriante', 'arrancada', 'plantada junto a rios', 'B', 'Oséias 10:1: "Israel é vide luxuriante, que dá o fruto para si mesmo." A prosperidade existia, mas era egoísta: quanto mais fruto, mais altares idólatras o povo erguia.', 'A planta era viçosa, mas o fruto era só para si mesma.', 'texto_biblico', 31),
('00000000-0000-4000-8000-010000000217', 'oseias', 10, 'Complete Oséias 10:12: "Arai o campo de ___".', 'medio', 'trigo', 'pousio', 'cevada', 'batalha', 'B', 'Oséias 10:12: "Semeai para vós outros em justiça, ceifai segundo a misericórdia; arai o campo de pousio; porque é tempo de buscar ao Senhor." Pousio é a terra descansada que precisa ser arada: o coração endurecido precisava ser quebrado pelo arrependimento.', 'É a terra que ficou sem plantar e endureceu.', 'texto_biblico', 32),
('00000000-0000-4000-8000-010000000218', 'oseias', 10, 'Segundo Oséias 10:7, o rei de Samaria será destruído como…', 'medio', 'palha no fogo', 'espuma sobre a água', 'pó ao vento', 'cera diante do fogo', 'B', 'Oséias 10:7: "O rei de Samaria será destruído como a espuma sobre a face da água." A monarquia do Norte, instável e cheia de golpes, desapareceria com facilidade diante do juízo.', 'É algo que some na superfície da água em segundos.', 'texto_biblico', 33),
('00000000-0000-4000-8000-010000000219', 'oseias', 11, 'Complete Oséias 11:4: "Com cordas humanas os atraí, com laços de ___".', 'medio', 'ferro', 'amor', 'ouro', 'guerra', 'B', 'Oséias 11:4: "Com cordas humanas os atraí, com laços de amor; fui para eles como quem tira o jugo de sobre as suas queixadas e lhes dou de comer." É uma das mais ternas descrições do cuidado de Deus em todo o Antigo Testamento.', 'É com isso que Deus atrai, não com violência.', 'texto_biblico', 34),
('00000000-0000-4000-8000-010000000220', 'oseias', 12, 'Segundo Oséias 12:3, quem pegou o calcanhar do irmão ainda no ventre?', 'medio', 'Esaú', 'Jacó', 'José', 'Benjamim', 'B', 'Oséias 12:3-4: "No ventre pegou do calcanhar de seu irmão; no seu vigor lutou com Deus; lutou com o anjo e prevaleceu." O profeta usa a história de Jacó (Gênesis 25:26; 32:24-30) como lição para os descendentes.', 'O nome dele está ligado à palavra "calcanhar".', 'texto_biblico', 35),
('00000000-0000-4000-8000-010000000301', 'oseias', 2, 'Em Oséias 2:19, com qual palavra começa a promessa do desposório: "Desposar-te-ei comigo em ___"?', 'dificil', 'Justiça', 'Paz', 'Glória', 'Alegria', 'A', 'Oséias 2:19: "Desposar-te-ei comigo em justiça, em juízo, em benignidade e em misericórdias." A sequência justiça–juízo–benignidade–misericórdia–fidelidade (v. 20) descreve o caráter da aliança restaurada.', 'É a primeira de cinco palavras; a última é "fidelidade".', 'texto_biblico', 36),
('00000000-0000-4000-8000-010000000302', 'oseias', 4, 'Complete Oséias 4:19: "O vento os envolveu nas suas ___".', 'dificil', 'mãos', 'asas', 'redes', 'cordas', 'B', 'Oséias 4:19: "O vento os envolveu nas suas asas, e envergonhar-se-ão por causa dos seus sacrifícios." O juízo levaria o povo como o vento carrega a palha; a idolatria terminaria em vergonha.', 'O vento é retratado como uma grande ave que carrega o povo.', 'texto_biblico', 37),
('00000000-0000-4000-8000-010000000303', 'oseias', 5, 'Segundo Oséias 5:13, Efraim, ao ver sua enfermidade, recorreu ao rei…', 'dificil', 'Jarebe', 'Senaqueribe', 'Faraó', 'Ben-Hadade', 'A', 'Oséias 5:13: "Efraim viu a sua enfermidade, e Judá, a sua chaga; foi Efraim para a Assíria e enviou mensageiros ao rei Jarebe." Jarebe ("o que contende/defende") é provavelmente um título irônico do rei assírio, que de nada valeria: "ele não poderá curar-vos".', 'É um nome que aparece só aqui e em 10:6, ligado à Assíria.', 'texto_biblico', 38),
('00000000-0000-4000-8000-010000000304', 'oseias', 5, 'Complete Oséias 5:1: os sacerdotes foram "um laço em Mispá e rede estendida sobre o ___".', 'dificil', 'Carmelo', 'Tabor', 'Hermom', 'Gerizim', 'B', 'Oséias 5:1: "Ouvi isto, ó sacerdotes... porque fostes um laço em Mispá e rede estendida sobre o Tabor." Em vez de guiar o povo, os líderes religiosos eram armadilhas; Mispá e Tabor eram lugares altos ligados ao culto corrupto.', 'É o monte isolado da Galileia, palco da Transfiguração segundo a tradição.', 'texto_biblico', 39),
('00000000-0000-4000-8000-010000000305', 'oseias', 6, 'Complete Oséias 6:7: "Mas eles, como ___, transgrediram a aliança".', 'dificil', 'Caim', 'Adão', 'Saul', 'Acabe', 'B', 'Oséias 6:7: "Mas eles, como Adão, transgrediram a aliança e se houveram aleivosamente contra mim." (Algumas traduções leem "em Adã", nome de cidade; a ARA segue "como Adão", ligando a quebra da aliança à queda no Éden.)', 'É o primeiro homem, que quebrou a primeira aliança no Éden.', 'texto_biblico', 40),
('00000000-0000-4000-8000-010000000306', 'oseias', 6, 'Segundo Oséias 6:8, Gileade é descrita como…', 'dificil', 'cidade de malfeitores', 'terra de fartura', 'refúgio dos justos', 'fonte de bálsamo', 'A', 'Oséias 6:8: "Gileade é cidade de malfeitores, manchada de sangue." A região da Transjordânia, famosa pelo "bálsamo de Gileade", é denunciada pela violência; o versículo seguinte acusa bandos de sacerdotes que assassinavam em Siquém (6:9).', 'A famosa terra do bálsamo é acusada de violência e sangue.', 'texto_biblico', 41),
('00000000-0000-4000-8000-010000000307', 'oseias', 7, 'Complete Oséias 7:9: estranhos devoram a força de Efraim "sem que ele o saiba" e…', 'dificil', 'os filhos o abandonaram', 'cabelos brancos se espalharam por ele', 'os celeiros se esvaziaram', 'os inimigos cercaram os muros', 'B', 'Oséias 7:9: "Estranhos lhe devoram a força, e ele não o sabe; também cabelos brancos já se espalham por ele, e ele não o sabe." A decadência é imperceptível: Israel envelhecia espiritualmente sem perceber.', 'É um sinal de velhice que ele nem percebia.', 'texto_biblico', 42),
('00000000-0000-4000-8000-010000000308', 'oseias', 9, 'Em Oséias 9:9, a corrupção de Israel é comparada aos dias de…', 'dificil', 'Gibeá', 'Jericó', 'Ai', 'Hazor', 'A', 'Oséias 9:9: "Aprofundaram-se na corrupção, como nos dias de Gibeá." Gibeá ficou marcada pelo crime brutal contra a concubina do levita (Juízes 19), que gerou guerra civil. Comparar Israel a Gibeá é dizer que o povo atingiu o fundo moral.', 'É a cidade do crime narrado em Juízes 19.', 'historico', 43),
('00000000-0000-4000-8000-010000000309', 'oseias', 10, 'Segundo Oséias 10:14, quem destruiu Bete-Arbel no dia da batalha?', 'dificil', 'Nabucodonosor', 'Salman', 'Sisaque', 'Tilgate-Pilneser', 'B', 'Oséias 10:14: "Crescerá o tumulto entre o teu povo, e todas as tuas fortalezas serão destruídas, como Salman destruiu a Bete-Arbel no dia da batalha." Trata-se de uma destruição exemplar do passado, usada como aviso do que viria sobre Israel.', 'O nome começa com "S" e aparece uma única vez em todo o livro.', 'texto_biblico', 44),
('00000000-0000-4000-8000-010000000310', 'oseias', 10, 'Complete Oséias 10:8: "Dirão aos montes: Cobri-nos! E aos outeiros: ___!"', 'dificil', 'Escondei-nos', 'Caí sobre nós', 'Guardai-nos', 'Livrai-nos', 'B', 'Oséias 10:8: "Dirão aos montes: Cobri-nos! E aos outeiros: Caí sobre nós!" No desespero do juízo, o povo preferiria ser soterrado a encarar a Deus. Jesus citou essas palavras a caminho da cruz (Lucas 23:30).', 'Jesus repetiu esse clamor no caminho ao Calvário.', 'texto_biblico', 45),
('00000000-0000-4000-8000-010000000311', 'oseias', 12, 'Complete Oséias 12:7: "É mercador; tem ___ enganosa em sua mão".', 'dificil', 'balança', 'espada', 'medida de trigo', 'moeda', 'A', 'Oséias 12:7: "É mercador; tem balança enganosa em sua mão; ama a opressão." A desonestidade no comércio é denunciada como forma de opressão contra o próximo — tema comum também em Amós 8:5.', 'É o instrumento do comércio desonesto.', 'texto_biblico', 46),
('00000000-0000-4000-8000-010000000312', 'oseias', 12, 'Segundo Oséias 12:12, Jacó fugiu para o campo de…', 'dificil', 'Edom', 'Moabe', 'Arã (Síria)', 'Midian', 'C', 'Oséias 12:12: "Jacó fugiu para o campo da Síria, e Israel serviu por mulher e por mulher guardou o rebanho." O profeta recorda que o patriarca começou como servo humilde — contraste com o orgulho dos descendentes enriquecidos.', 'Foi para lá que ele foi trabalhar para Labão.', 'texto_biblico', 47),
('00000000-0000-4000-8000-010000000313', 'oseias', 12, 'Complete Oséias 12:13: "Por um ___ o Senhor tirou a Israel do Egito".', 'dificil', 'exército', 'rei', 'profeta', 'sinal no céu', 'C', 'Oséias 12:13: "Mas o Senhor, por meio de um profeta, fez subir a Israel do Egito, e, por um profeta, foi ele guardado." O profeta é Moisés: a libertação veio pela Palavra de Deus, não por força humana — e os profetas continuavam sendo os guardas de Israel.', 'É o ministério de Moisés, que tirou o povo do Egito.', 'texto_biblico', 48),
('00000000-0000-4000-8000-010000000314', 'oseias', 13, 'Complete Oséias 13:7: "Serei, pois, para eles como leão; como ___ espreitarei junto ao caminho".', 'dificil', 'leopardo', 'lobo', 'águia', 'serpente', 'A', 'Oséias 13:7-8: "Serei, pois, para eles como leão; como leopardo espreitarei junto ao caminho. Como ursa roubada dos seus filhos, os encontrarei." Três predadores em sequência mostram a certeza do juízo sobre um povo que esqueceu a Deus (13:6).', 'É um felino veloz, antes da ursa do versículo seguinte.', 'texto_biblico', 49),
('00000000-0000-4000-8000-010000000315', 'oseias', 14, 'Complete Oséias 14:5: "Serei para Israel como ___; ele florescerá como o lírio".', 'dificil', 'o sol', 'a chuva temporã', 'o orvalho', 'o rio', 'C', 'Oséias 14:5: "Serei para Israel como orvalho, ele florescerá como o lírio e lançará as suas raízes como o cedro do Líbano." O orvalho silencioso contrasta com a tempestade do juízo: a restauração viria suave, pela graça.', 'É a umidade silenciosa que molha a relva de madrugada.', 'texto_biblico', 50)
on conflict (id) do nothing;

-- ===== OBADIAS (50) =====
insert into public.questions
  (id, book_id, chapter, question, difficulty, option_a, option_b, option_c, option_d,
   correct_answer, explanation, hint, source_type, order_index)
values
('00000000-0000-4000-8000-020000000101', 'obadias', 1, 'Quantos capítulos tem o livro de Obadias?', 'facil', 'Um', 'Três', 'Quatro', 'Doze', 'A', 'Obadias possui um único capítulo, com 21 versículos. É o menor livro do Antigo Testamento e o quarto entre os Profetas Menores (depois de Amós e antes de Jonas).', 'É o menor livro do Antigo Testamento.', 'texto_biblico', 1),
('00000000-0000-4000-8000-020000000102', 'obadias', 1, 'Quantos versículos tem o livro de Obadias?', 'facil', '12', '21', '31', '48', 'B', 'O capítulo único de Obadias tem 21 versículos: os versículos 1 a 16 anunciam o juízo contra Edom e os versículos 17 a 21 prometem o livramento de Sião e o reino do Senhor.', 'É o triplo de sete.', 'texto_biblico', 2),
('00000000-0000-4000-8000-020000000103', 'obadias', 1, 'O que significa o nome "Obadias"?', 'facil', 'Deus é forte', 'Servo do Senhor', 'A quem Deus ajuda', 'Paz do Senhor', 'B', 'Obadias (em hebraico, Obadyah) significa "servo do Senhor" ou "adorador do Senhor". Nada mais se sabe sobre o profeta além do nome: toda a atenção do livro está na mensagem, não no mensageiro.', 'Começa com "servo" — aquele que serve.', 'texto_biblico', 3),
('00000000-0000-4000-8000-020000000104', 'obadias', 1, 'Contra qual nação é dirigida a profecia de Obadias?', 'facil', 'Moabe', 'Amom', 'Edom', 'Filístia', 'C', 'Obadias 1: "Assim diz o Senhor Deus a respeito de Edom." Todo o livro é uma sentença contra Edom, nação descendente de Esaú, por sua soberba e pela violência contra Judá.', 'É a nação descendente de Esaú, irmão de Jacó.', 'texto_biblico', 4),
('00000000-0000-4000-8000-020000000105', 'obadias', 1, 'De qual patriarca descendiam os edomitas?', 'facil', 'Jacó', 'Isaque, por meio de Jacó', 'Esaú', 'Ismael', 'C', 'Os edomitas descendiam de Esaú, também chamado Edom (Gênesis 25:30; 36:1). Por isso Obadias chama Edom de "monte de Esaú" (v. 8-9, 19, 21) e de "casa de Esaú" (v. 18).', 'É o irmão gêmeo de Jacó, que vendeu a primogenitura.', 'texto_biblico', 5),
('00000000-0000-4000-8000-020000000106', 'obadias', 1, 'Quem era o "irmão" contra quem Edom praticou violência, segundo Obadias 10?', 'facil', 'Ismael', 'Jacó', 'Labão', 'Ló', 'B', 'Obadias 10: "Por causa da violência feita a teu irmão Jacó, cobrir-te-á a vergonha." Edom e Israel eram povos irmãos — descendentes de Esaú e Jacó — e por isso o crime de Edom foi ainda mais grave.', 'É o outro nome de Israel, pai das doze tribos.', 'texto_biblico', 6),
('00000000-0000-4000-8000-020000000107', 'obadias', 1, 'Complete Obadias 4: "Ainda que te eleves como ___".', 'facil', 'o cedro', 'a águia', 'a torre', 'o monte', 'B', 'Obadias 4: "Se te elevares como águia e puseres o teu ninho entre as estrelas, dali te derribarei, diz o Senhor." Nem a altura das fortalezas de Edom nas montanhas o livraria do juízo.', 'É a ave que voa mais alto e faz ninho nos penhascos.', 'texto_biblico', 7),
('00000000-0000-4000-8000-020000000108', 'obadias', 1, 'Onde habitava Edom, segundo Obadias 3?', 'facil', 'Em tendas no deserto', 'Nas fendas das rochas, em morada alta', 'Em ilhas no mar', 'Em cavernas junto ao Jordão', 'B', 'Obadias 3: "ó tu que habitas nas fendas das rochas, cuja morada é alta." Edom ocupava a região montanhosa de Seir, com cidades fortificadas nas rochas (como Sela, a futura Petra), e confiava nessas defesas naturais.', 'Era um lugar alto, entre pedras, que parecia inexpugnável.', 'texto_biblico', 8),
('00000000-0000-4000-8000-020000000109', 'obadias', 1, 'Como termina o livro de Obadias (v. 21)?', 'facil', '"e o reino será do Senhor"', '"e chorarão sobre Edom"', '"e haverá paz para sempre"', '"e se calarão as nações"', 'A', 'Obadias 21: "Subirão salvadores ao monte Sião, para julgarem o monte de Esaú; e o reino será do Senhor." O livro que começa com guerra contra Edom termina com a vitória universal do Reino de Deus.', 'É a frase que entrega o reino a Deus.', 'texto_biblico', 9),
('00000000-0000-4000-8000-020000000110', 'obadias', 1, 'Segundo Obadias 3, o que enganou a Edom?', 'facil', 'Os falsos profetas', 'A soberba do seu coração', 'O ouro de Ofir', 'Os exércitos da Assíria', 'B', 'Obadias 3: "A soberba do teu coração te enganou." O pecado-raiz de Edom foi o orgulho: confiava nas montanhas, nos aliados, nos sábios e nos valentes — e dizia: "Quem me derribará?"', 'É o pecado de quem se acha inalcançável.', 'texto_biblico', 10),
('00000000-0000-4000-8000-020000000111', 'obadias', 1, 'O que Deus faria com Edom, ainda que pusesse seu ninho entre as estrelas?', 'facil', 'O exaltaria ainda mais', 'O derribaria', 'O esconderia', 'O esqueceria', 'B', 'Obadias 4: "dali te derribarei, diz o Senhor." Nenhuma altura — nem fortalezas nas rochas, nem orgulho que chega às estrelas — pode resistir ao juízo de Deus.', 'É o oposto de exaltar: jogar por terra.', 'texto_biblico', 11),
('00000000-0000-4000-8000-020000000112', 'obadias', 1, 'Por que Edom seria coberto de vergonha e exterminado, segundo Obadias 10?', 'facil', 'Por adorar o bezerro de ouro', 'Por sua preguiça no trabalho', 'Pela violência feita ao irmão Jacó', 'Por recusar pagar impostos', 'C', 'Obadias 10: "Por causa da violência feita a teu irmão Jacó, cobrir-te-á a vergonha, e serás exterminado para sempre." Quando Jerusalém caiu, Edom se alegrou, saqueou e entregou os fugitivos (v. 11-14).', 'Foi um crime contra o povo irmão.', 'texto_biblico', 12),
('00000000-0000-4000-8000-020000000113', 'obadias', 1, 'Segundo Obadias 15, o que está perto sobre todas as nações?', 'facil', 'O Dia do Senhor', 'O ano do jubileu', 'A festa dos tabernáculos', 'O sábado da terra', 'A', 'Obadias 15: "Porque o Dia do Senhor está perto, sobre todas as nações." O juízo sobre Edom é apresentado como parte do grande Dia em que Deus julgará todos os povos — tema central dos profetas.', 'É o grande dia do juízo de Deus sobre as nações.', 'texto_biblico', 13),
('00000000-0000-4000-8000-020000000114', 'obadias', 1, 'Complete Obadias 15: "Como tu fizeste, assim se fará ___".', 'facil', 'ao teu vizinho', 'contigo', 'aos teus filhos', 'naquele dia', 'B', 'Obadias 15: "como tu fizeste, assim se fará contigo; o teu feito tornará sobre a tua cabeça." É a lei da retribuição: Edom seria tratado exatamente como tratou Judá.', 'A medida usada contra os outros voltaria contra ele mesmo.', 'texto_biblico', 14),
('00000000-0000-4000-8000-020000000115', 'obadias', 1, 'Sobre qual cidade estrangeiros lançaram sortes, segundo Obadias 11?', 'facil', 'Samaria', 'Damasco', 'Jerusalém', 'Tiro', 'C', 'Obadias 11: estrangeiros "lançaram sortes sobre Jerusalém, tu mesmo eras um deles." O versículo descreve a queda de Jerusalém, quando Edom se uniu aos invasores em vez de ajudar o povo irmão.', 'É a capital de Judá, onde ficava o templo.', 'texto_biblico', 15),
('00000000-0000-4000-8000-020000000201', 'obadias', 1, 'Como o livro de Obadias se apresenta logo no primeiro versículo?', 'medio', 'Lamentação de Obadias', 'Visão de Obadias', 'Cântico de Obadias', 'Carta de Obadias', 'B', 'Obadias 1: "Visão de Obadias: Assim diz o Senhor Deus a respeito de Edom." O livro é uma visão profética — Deus mostrou ao profeta a sentença contra Edom.', 'É algo que Deus mostrou ao profeta, não algo que ele escreveu por si.', 'texto_biblico', 16),
('00000000-0000-4000-8000-020000000202', 'obadias', 1, 'Complete Obadias 1: "Assim diz o ___ a respeito de Edom".', 'medio', 'rei de Judá', 'Senhor Deus', 'anjo do Senhor', 'profeta aos povos', 'B', 'Obadias 1: "Assim diz o Senhor Deus a respeito de Edom." A fórmula mostra que a sentença contra Edom vem do próprio Deus, não de opinião humana.', 'É a fórmula clássica dos profetas: "Assim diz o…".', 'texto_biblico', 17),
('00000000-0000-4000-8000-020000000203', 'obadias', 1, 'Qual mensagem o mensageiro levou às nações, segundo Obadias 1?', 'medio', 'Trazei ofertas a Sião', 'Levantai-vos contra ela para a guerra', 'Fugi para os montes', 'Guardai o sábado', 'B', 'Obadias 1: "às nações foi enviado mensageiro, dizendo: Levantai-vos, e levantemo-nos contra ela para a guerra." Deus convoca as próprias nações para executar o juízo contra Edom.', 'Era uma convocação para lutar contra Edom.', 'texto_biblico', 18),
('00000000-0000-4000-8000-020000000204', 'obadias', 1, 'Complete Obadias 2: "Eis que te fiz ___ entre as nações".', 'medio', 'grande', 'pequeno', 'rico', 'temido', 'B', 'Obadias 2: "Eis que te fiz pequeno entre as nações; tu és mui desprezado." O orgulhoso Edom, que se julgava grande nas montanhas, seria reduzido e desprezado entre os povos.', 'É o oposto do que Edom pensava de si mesmo.', 'texto_biblico', 19),
('00000000-0000-4000-8000-020000000205', 'obadias', 1, 'Segundo Obadias 5, os vindimadores (colhedores de uva) deixariam o quê?', 'medio', 'Alguns cachos', 'As folhas', 'Nada, levariam tudo', 'Apenas as uvas verdes', 'A', 'Obadias 5: "Se a ti viessem os vindimadores, não deixariam alguns cachos?" Até ladrões e colhedores deixam restos — mas o saque de Edom seria total, sem sobra alguma (v. 6).', 'Até os ladrões mais gananciosos deixam alguma sobra.', 'texto_biblico', 20),
('00000000-0000-4000-8000-020000000206', 'obadias', 1, 'Complete Obadias 6: "Como foram esquadrinhados os de ___!"', 'medio', 'Jacó', 'Esaú', 'Ismael', 'Ló', 'B', 'Obadias 6: "Como foram esquadrinhados os de Esaú! Como foram explorados os seus tesouros escondidos!" Ser esquadrinhado é ser revistado por completo: nada de Edom escaparia do saque.', 'É o outro nome do pai dos edomitas.', 'texto_biblico', 21),
('00000000-0000-4000-8000-020000000207', 'obadias', 1, 'Segundo Obadias 6, o que seria explorado (descoberto) em Edom?', 'medio', 'As minas de cobre', 'Os tesouros escondidos', 'As rotas de caravanas', 'Os poços de água', 'B', 'Obadias 6: "Como foram explorados os seus tesouros escondidos!" Edom controlava rotas comerciais e acumulara riquezas; tudo seria descoberto e saqueado.', 'Eram riquezas que Edom julgava bem guardadas.', 'texto_biblico', 22),
('00000000-0000-4000-8000-020000000208', 'obadias', 1, 'Segundo Obadias 7, até onde os aliados levariam Edom?', 'medio', 'Até o mar', 'Até as fronteiras', 'Até o deserto', 'Até o rio', 'B', 'Obadias 7: "Todos os teus aliados te levaram para as fronteiras." Os supostos amigos expulsariam Edom do seu próprio território: a primeira traição de uma sequência — engano, armadilha e falta de entendimento.', 'Seria expulso até o limite do próprio território.', 'texto_biblico', 23),
('00000000-0000-4000-8000-020000000209', 'obadias', 1, 'Complete Obadias 7: "Os que comem o teu pão puseram ___ debaixo de ti".', 'medio', 'um banquete', 'uma armadilha', 'um tapete', 'um trono', 'B', 'Obadias 7: "os que comem o teu pão puseram armadilha debaixo de ti." Comer o pão de alguém era sinal de aliança; os aliados de Edom quebrariam a aliança e o trairiam.', 'Quem comia à mesa com ele preparava uma traição.', 'texto_biblico', 24),
('00000000-0000-4000-8000-020000000210', 'obadias', 1, 'Segundo Obadias 8, quem pereceria em Edom naquele dia?', 'medio', 'Os pastores', 'Os sábios', 'Os lavradores', 'Os estrangeiros', 'B', 'Obadias 8: "Não farei perecer os sábios de Edom e o entendimento do monte de Esaú?" Edom era famosa pela sabedoria (Temã; Elifaz, amigo de Jó, era temanita) — e até isso Deus tiraria.', 'Edom se orgulhava deles; Temã era famosa por isso.', 'texto_biblico', 25),
('00000000-0000-4000-8000-020000000211', 'obadias', 1, 'Segundo Obadias 9, os valentes de qual lugar estariam atemorizados?', 'medio', 'Temã', 'Bozra', 'Sela', 'Seir', 'A', 'Obadias 9: "Também os teus valentes, ó Temã, estarão atemorizados." Temã era uma cidade/distrito de Edom, famosa pelos sábios e guerreiros. Até os valentes tremeriam no dia do juízo.', 'É a terra de Elifaz, o amigo de Jó.', 'texto_biblico', 26),
('00000000-0000-4000-8000-020000000212', 'obadias', 1, 'O que os estrangeiros lançaram sobre Jerusalém, segundo Obadias 11?', 'medio', 'Flechas', 'Sortes', 'Redes', 'Tochas', 'B', 'Obadias 11: estrangeiros "lançaram sortes sobre Jerusalém." Lançar sortes era sortear o despojo da cidade conquistada — e Edom participou da partilha como um dos invasores.', 'Era o sorteio para dividir os despojos da cidade.', 'texto_biblico', 27),
('00000000-0000-4000-8000-020000000213', 'obadias', 1, 'Complete Obadias 11: diante da queda de Jerusalém, "tu mesmo eras ___ deles".', 'medio', 'o juiz', 'um', 'o inimigo', 'o refúgio', 'B', 'Obadias 11: "tu mesmo eras um deles." Edom não ficou neutra: agiu como um dos invasores de Jerusalém. A neutralidade diante do mal do irmão já seria culpa; a participação ativa foi crime.', 'Edom se fez igual aos invasores.', 'texto_biblico', 28),
('00000000-0000-4000-8000-020000000214', 'obadias', 1, 'Segundo Obadias 12, o que Edom não devia ter "alargado" no dia da angústia?', 'medio', 'Os celeiros', 'A boca', 'As fronteiras', 'Os exércitos', 'B', 'Obadias 12: "nem ter alargado a boca, no dia da angústia." Alargar a boca é zombar, escarnecer. Edom não apenas assistiu: alegrou-se e zombou da ruína de Judá.', 'É o gesto de quem zomba e escarnece.', 'texto_biblico', 29),
('00000000-0000-4000-8000-020000000215', 'obadias', 1, 'Segundo Obadias 13, Edom não devia ter entrado pela ___ do povo de Deus.', 'medio', 'porta', 'muralha', 'praça', 'fonte', 'A', 'Obadias 13: "Não devias ter entrado pela porta do meu povo, no dia da sua calamidade." Edom invadiu as cidades de Judá no dia da calamidade para saquear, em vez de socorrer.', 'É a entrada da cidade, por onde os invasores passaram.', 'texto_biblico', 30),
('00000000-0000-4000-8000-020000000216', 'obadias', 1, 'Segundo Obadias 13, Edom lançou mão dos ___ de Judá.', 'medio', 'filhos', 'bens', 'altares', 'documentos', 'B', 'Obadias 13: "nem ter lançado mão dos seus bens, no dia da sua calamidade." Aproveitando-se da desgraça do irmão, Edom saqueou os bens de Judá.', 'Foram as riquezas e posses que ele saqueou.', 'texto_biblico', 31),
('00000000-0000-4000-8000-020000000217', 'obadias', 1, 'Onde Edom se posicionou para exterminar os que escapavam, segundo Obadias 14?', 'medio', 'Nos portos', 'Nas encruzilhadas', 'Nos montes', 'Nos vales', 'B', 'Obadias 14: "Nem ter parado nas encruzilhadas, para exterminares os que escapassem; nem ter entregado os que lhe restassem." Edom fechou as rotas de fuga e entregou os sobreviventes — o auge da crueldade.', 'É o cruzamento de caminhos, onde se intercepta quem foge.', 'texto_biblico', 32),
('00000000-0000-4000-8000-020000000218', 'obadias', 1, 'Segundo Obadias 16, o que todas as nações beberiam de contínuo?', 'medio', 'O vinho da alegria', 'O cálice do juízo de Deus', 'A água da vida', 'O leite da terra', 'B', 'Obadias 16: "como bebestes no meu santo monte, assim beberão, de contínuo, todas as nações." Beber o cálice é imagem do juízo divino (como em Jeremias 25 e Apocalipse 14): todas as nações ímpias provariam a ira de Deus.', 'É a bebida amarga da ira de Deus contra as nações.', 'texto_biblico', 33),
('00000000-0000-4000-8000-020000000219', 'obadias', 1, 'Segundo Obadias 17, onde haveria livramento?', 'medio', 'No monte das Oliveiras', 'No monte Sião', 'No monte Sinai', 'No monte Carmelo', 'B', 'Obadias 17: "Mas, no monte Sião, haverá livramento; o monte será santo." Enquanto Edom seria exterminado, Sião (Jerusalém, o povo de Deus) seria preservada e santificada.', 'É o monte de Jerusalém, onde ficava o templo.', 'texto_biblico', 34),
('00000000-0000-4000-8000-020000000220', 'obadias', 1, 'Em Obadias 18, a casa de Jacó será fogo e a casa de Esaú será…', 'medio', 'água', 'palha', 'pedra', 'ferro', 'B', 'Obadias 18: "A casa de Jacó será fogo... e a casa de Esaú, palha." O povo de Deus, instrumento do juízo, consumiria Edom como o fogo consome a palha — e "ninguém mais restará da casa de Esaú".', 'É o que o fogo consome mais rápido.', 'texto_biblico', 35),
('00000000-0000-4000-8000-020000000301', 'obadias', 1, 'Em Obadias 18, a casa de José será…', 'dificil', 'chama', 'vento', 'martelo', 'espada', 'A', 'Obadias 18: "A casa de Jacó será fogo, e a casa de José, chama, e a casa de Esaú, palha." Jacó (Judá) e José (as tribos do Norte, Efraim/Manassés) aparecem reunidos como instrumento único do juízo — promessa de reunificação de Israel.', 'Completa o trio: fogo, ___, palha.', 'texto_biblico', 36),
('00000000-0000-4000-8000-020000000302', 'obadias', 1, 'Segundo Obadias 19, quem possuiria o monte de Esaú?', 'dificil', 'Os do Neguebe (Sul)', 'Os de Tiro', 'Os de Damasco', 'Os do Egito', 'A', 'Obadias 19: "Os do Neguebe possuirão o monte de Esaú." O Neguebe é a região sul de Judá, vizinha de Edom: os vizinhos do sul herdariam o território do orgulhoso vizinho exterminado.', 'É a região do sul de Judá, vizinha de Edom.', 'texto_biblico', 37),
('00000000-0000-4000-8000-020000000303', 'obadias', 1, 'Segundo Obadias 19, os da planície (Sefelá) possuiriam…', 'dificil', 'os moabitas', 'os filisteus', 'os amonitas', 'os sírios', 'B', 'Obadias 19: "os da planície, os filisteus." A Sefelá é a planície baixa entre a montanha de Judá e a costa filisteia. O povo de Deus retomaria até as terras dos antigos opressores.', 'É o povo da costa, inimigo de Israel desde Sansão e Davi.', 'texto_biblico', 38),
('00000000-0000-4000-8000-020000000304', 'obadias', 1, 'Segundo Obadias 19, Benjamim possuiria…', 'dificil', 'a Galileia', 'a Gileade', 'o Neguebe', 'a Sefelá', 'B', 'Obadias 19: "Benjamim possuirá a Gileade." A restauração ampliaria as fronteiras: a pequena tribo de Benjamim herdaria a fértil Gileade, do outro lado do Jordão.', 'É a terra além do Jordão, famosa pelo bálsamo.', 'texto_biblico', 39),
('00000000-0000-4000-8000-020000000305', 'obadias', 1, 'Segundo Obadias 20, os exilados de Israel possuiriam terras até…', 'dificil', 'Sarepta', 'Nínive', 'Babilônia', 'Menfis', 'A', 'Obadias 20: "Os exilados deste exército dos filhos de Israel possuirão os cananeus até Sarepta." Sarepta era cidade fenícia da costa (onde Elias foi sustentado pela viúva, 1 Reis 17): Israel se expandiria até o litoral norte.', 'É a cidade fenícia onde Elias multiplicou a farinha da viúva.', 'texto_biblico', 40),
('00000000-0000-4000-8000-020000000306', 'obadias', 1, 'Segundo Obadias 20, os cativos de Jerusalém estavam em…', 'dificil', 'Sefarade', 'Tarsis', 'Patros', 'Elão', 'A', 'Obadias 20: "os cativos de Jerusalém, que estão em Sefarade, possuirão as cidades do Sul." Sefarade era uma terra distante de exílio (a tradição judaica a identificou com a Espanha, dando nome aos judeus sefarditas).', 'É o lugar que deu nome aos judeus sefarditas.', 'texto_biblico', 41),
('00000000-0000-4000-8000-020000000307', 'obadias', 1, 'Segundo Obadias 21, quem subiria ao monte Sião?', 'dificil', 'Guerreiros', 'Salvadores', 'Sacerdotes', 'Anjos', 'B', 'Obadias 21: "Subirão salvadores ao monte Sião, para julgarem o monte de Esaú." Deus levantaria libertadores — como os juízes do passado — para executar a sentença sobre Edom.', 'São libertadores, como os juízes que Deus levantava.', 'texto_biblico', 42),
('00000000-0000-4000-8000-020000000308', 'obadias', 1, 'Para que os salvadores subiriam ao monte Sião, segundo Obadias 21?', 'dificil', 'Para oferecer sacrifícios', 'Para julgarem o monte de Esaú', 'Para coroar um rei', 'Para edificar muralhas', 'B', 'Obadias 21: os salvadores subiriam "para julgarem o monte de Esaú." O monte de Esaú (Edom) seria julgado a partir do monte Sião (o povo de Deus): a justiça final pertence ao Senhor.', 'Eles executariam a sentença contra Edom.', 'texto_biblico', 43),
('00000000-0000-4000-8000-020000000309', 'obadias', 1, 'Complete Obadias 16: as nações "beberão, e engolirão, e serão como se nunca tivessem ___".', 'dificil', 'pecado', 'sido', 'nascido', 'voltado', 'B', 'Obadias 16: "beberão, e engolirão, e serão como se nunca tivessem sido." O juízo apagaria as nações ímpias da história — enquanto o povo de Deus herdaria a terra (v. 17).', 'Seriam apagadas da existência.', 'texto_biblico', 44),
('00000000-0000-4000-8000-020000000310', 'obadias', 1, 'Complete Obadias 18: "ninguém mais restará da casa de ___".', 'dificil', 'Jacó', 'José', 'Esaú', 'Judá', 'C', 'Obadias 18: "ninguém mais restará da casa de Esaú, porque o Senhor o disse." A sentença é total e irreversível — selada pela autoridade de quem fala: o próprio Senhor.', 'É a casa que seria consumida como palha.', 'texto_biblico', 45),
('00000000-0000-4000-8000-020000000311', 'obadias', 1, 'De onde Deus tiraria o entendimento, segundo Obadias 8?', 'dificil', 'Do palácio de Judá', 'Do monte de Esaú', 'Das escolas do Egito', 'Das praças de Tiro', 'B', 'Obadias 8: "Não farei perecer os sábios de Edom e o entendimento do monte de Esaú?" O "monte de Esaú" é Edom, a nação montanhosa: até sua famosa sabedoria seria aniquilada.', 'É outro nome para a própria terra de Edom.', 'texto_biblico', 46),
('00000000-0000-4000-8000-020000000312', 'obadias', 1, 'Como termina Obadias 7? "…não há nele ___".', 'dificil', 'misericórdia', 'entendimento', 'força', 'temor', 'B', 'Obadias 7 termina: "não há nele entendimento." Edom, famosa pelos sábios, não perceberia nem a traição dos próprios aliados — o juízo começaria pela cegueira.', 'Faltaria a ele justamente aquilo de que se orgulhava: a sabedoria.', 'texto_biblico', 47),
('00000000-0000-4000-8000-020000000313', 'obadias', 1, 'Segundo Obadias 9, de onde cada um seria exterminado "pela matança"?', 'dificil', 'Do vale do Jordão', 'Do monte de Esaú', 'Das cidades da costa', 'Do deserto do Neguebe', 'B', 'Obadias 9: os valentes de Temã tremeriam, "para que do monte de Esaú seja cada um exterminado pela matança." Ninguém escaparia: o extermínio seria completo.', 'É o mesmo "monte" citado nos versículos 8, 19 e 21.', 'texto_biblico', 48),
('00000000-0000-4000-8000-020000000314', 'obadias', 1, 'Segundo Obadias 19, além dos campos de Efraim, quais outros campos seriam possuídos?', 'dificil', 'Os campos de Samaria', 'Os campos de Belém', 'Os campos de Jericó', 'Os campos de Dã', 'A', 'Obadias 19: "possuirão também os campos de Efraim e os campos de Samaria." Efraim e Samaria representam o antigo reino do Norte: a restauração reuniria as terras de todo o Israel.', 'É a capital do antigo reino do Norte.', 'texto_biblico', 49),
('00000000-0000-4000-8000-020000000315', 'obadias', 1, 'Segundo Obadias 20, os cativos de Jerusalém possuiriam as cidades de qual região?', 'dificil', 'Do Norte', 'Do Sul (Neguebe)', 'Da costa', 'Da Transjordânia', 'B', 'Obadias 20: "os cativos de Jerusalém, que estão em Sefarade, possuirão as cidades do Sul." Os exilados voltariam para herdar as cidades do Neguebe — possivelmente as mesmas terras antes ocupadas por Edom.', 'É a mesma região citada no versículo 19: o Neguebe.', 'texto_biblico', 50)
on conflict (id) do nothing;

-- ===== JONAS (50) =====
insert into public.questions
  (id, book_id, chapter, question, difficulty, option_a, option_b, option_c, option_d,
   correct_answer, explanation, hint, source_type, order_index)
values
('00000000-0000-4000-8000-030000000101', 'jonas', 1, 'Quem era o pai do profeta Jonas?', 'facil', 'Amitai', 'Beeri', 'Joás', 'Diblaim', 'A', 'Jonas 1:1: "Veio a palavra do Senhor a Jonas, filho de Amitai." O mesmo profeta é citado em 2 Reis 14:25, onde profetizou a restauração das fronteiras de Israel nos dias de Jeroboão II.', 'O nome aparece logo no primeiro versículo do livro.', 'texto_biblico', 1),
('00000000-0000-4000-8000-030000000102', 'jonas', 1, 'O que Deus mandou Jonas fazer em Nínive?', 'facil', 'Morar lá como estrangeiro', 'Clamar contra ela', 'Comprar terras', 'Casar-se lá', 'B', 'Jonas 1:2: "Levanta-te, vai à grande cidade de Nínive e clama contra ela, porque a sua maldade subiu até mim." Clamar contra a cidade era anunciar o juízo de Deus sobre seus pecados.', 'Era anunciar em alta voz o juízo de Deus.', 'texto_biblico', 2),
('00000000-0000-4000-8000-030000000103', 'jonas', 1, 'Para onde Jonas fugiu, em vez de ir a Nínive?', 'facil', 'Para o Egito', 'Para Damasco', 'Para Társis', 'Para a Babilônia', 'C', 'Jonas 1:3: Jonas "se levantou para fugir de diante do Senhor, para Társis." Nínive ficava a nordeste; Társis, porto distante no oeste (possivelmente na Espanha): Jonas foi para a direção oposta.', 'Era um porto distante no oeste, na direção contrária.', 'texto_biblico', 3),
('00000000-0000-4000-8000-030000000104', 'jonas', 1, 'De qual porto Jonas partiu de navio?', 'facil', 'Jope', 'Tiro', 'Sidom', 'Gaza', 'A', 'Jonas 1:3: Jonas "desceu a Jope, e achou um navio que ia para Társis; pagou a passagem e embarcou nele." Jope (a atual Jafa) era o porto do litoral de Israel.', 'É o porto do litoral de Israel, hoje chamado Jafa.', 'texto_biblico', 4),
('00000000-0000-4000-8000-030000000105', 'jonas', 1, 'O que o Senhor lançou sobre o mar contra o navio de Jonas?', 'facil', 'Uma chuva de pedras', 'Um grande vento (tempestade)', 'Uma escuridão de três dias', 'Um exército de gafanhotos', 'B', 'Jonas 1:4: "Mas o Senhor lançou sobre o mar um forte vento, e fez-se no mar uma grande tempestade, e o navio estava a ponto de quebrar-se." A tempestade era a disciplina de Deus para alcançar o profeta fujão.', 'Foi uma grande tempestade que quase quebrou o navio.', 'texto_biblico', 5),
('00000000-0000-4000-8000-030000000106', 'jonas', 1, 'O que engoliu Jonas depois que ele foi lançado ao mar?', 'facil', 'Um tubarão', 'Uma baleia pequena', 'Um grande peixe', 'Um crocodilo', 'C', 'Jonas 1:17: "O Senhor deparou um grande peixe, para que tragasse a Jonas." O texto diz "grande peixe" (não especifica a espécie): Deus o preparou como instrumento de juízo e de livramento ao mesmo tempo.', 'O texto diz apenas que era "grande".', 'texto_biblico', 6),
('00000000-0000-4000-8000-030000000107', 'jonas', 1, 'Quanto tempo Jonas ficou dentro do peixe?', 'facil', 'Um dia e uma noite', 'Sete dias', 'Três dias e três noites', 'Quarenta dias', 'C', 'Jonas 1:17: "esteve Jonas três dias e três noites no ventre do peixe." Jesus apontou esse episódio como sinal da sua morte e ressurreição (Mateus 12:40).', 'É o mesmo número de dias de Jesus no túmulo.', 'texto_biblico', 7),
('00000000-0000-4000-8000-030000000108', 'jonas', 3, 'Em quantos dias Nínive seria subvertida, segundo a pregação de Jonas?', 'facil', 'Três dias', 'Sete dias', 'Doze dias', 'Quarenta dias', 'D', 'Jonas 3:4: "Ainda quarenta dias, e Nínive será subvertida." Quarenta é número frequente de prova na Bíblia (dilúvio, Sinai, deserto, jejum de Jesus).', 'É o mesmo número dos dias do dilúvio e do jejum de Jesus.', 'texto_biblico', 8),
('00000000-0000-4000-8000-030000000109', 'jonas', 3, 'Como os ninivitas reagiram à pregação de Jonas?', 'facil', 'Expulsaram o profeta da cidade', 'Creram em Deus, jejuaram e se vestiram de saco', 'Ignoraram e continuaram festejando', 'Prenderam Jonas por três dias', 'B', 'Jonas 3:5: "Os ninivitas creram em Deus, e proclamaram um jejum, e vestiram-se de panos de saco, desde o maior até ao menor." Foi um dos maiores arrependimentos coletivos registrados na Bíblia.', 'Eles creram, jejuaram e se humilharam.', 'texto_biblico', 9),
('00000000-0000-4000-8000-030000000110', 'jonas', 4, 'Quantos capítulos tem o livro de Jonas?', 'facil', 'Dois', 'Quatro', 'Seis', 'Doze', 'B', 'Jonas tem 4 capítulos: 1) a fuga e a tempestade; 2) a oração no ventre do peixe; 3) a pregação e o arrependimento de Nínive; 4) a ira de Jonas e a lição da planta.', 'É um dos livros mais curtos dos Profetas Menores.', 'texto_biblico', 10),
('00000000-0000-4000-8000-030000000111', 'jonas', 2, 'Complete Jonas 2:9: "A salvação vem do ___".', 'facil', 'mar', 'Senhor', 'rei', 'profeta', 'B', 'Jonas 2:9: "eu, com a voz do agradecimento, te oferecerei sacrifício; o que votei pagarei. Ao Senhor pertence a salvação!" No fundo do mar, Jonas confessou que só Deus salva.', 'É a grande confissão do livro: só Deus salva.', 'texto_biblico', 11),
('00000000-0000-4000-8000-030000000112', 'jonas', 1, 'O que os marinheiros lançaram para descobrir quem era o culpado pela tempestade?', 'facil', 'Redes', 'Âncoras', 'Sortes', 'Flechas', 'C', 'Jonas 1:7: "Vinde, e lancemos sortes, para que saibamos por causa de quem nos sobreveio este mal." Lançar sortes era um modo antigo de buscar a resposta de Deus (como em Provérbios 16:33).', 'Era um sorteio para revelar a vontade de Deus.', 'texto_biblico', 12),
('00000000-0000-4000-8000-030000000113', 'jonas', 1, 'O que Jonas disse aos marinheiros para fazerem com ele?', 'facil', 'Que o amarrassem ao mastro', 'Que o lançassem ao mar', 'Que o levassem de volta a Jope', 'Que o escondessem no porão', 'B', 'Jonas 1:12: "Levantai-me e lançai-me ao mar, e o mar se aquietará." Jonas sabia que a tempestade viera por sua causa e se ofereceu para salvar a tripulação.', 'Ele se ofereceu para salvar os companheiros.', 'texto_biblico', 13),
('00000000-0000-4000-8000-030000000114', 'jonas', 3, 'Ao ouvir a pregação, o rei de Nínive se cobriu de saco e se assentou…', 'facil', 'no trono de ouro', 'na cinza', 'no templo', 'no alto do muro', 'B', 'Jonas 3:6: o rei "levantou-se do seu trono, tirou de si as vestes reais, cobriu-se de saco e assentou-se sobre cinza." Do trono à cinza: o maior da cidade se humilhou como o menor.', 'É o pó cinzento símbolo de luto e arrependimento.', 'texto_biblico', 14),
('00000000-0000-4000-8000-030000000115', 'jonas', 4, 'Quantas pessoas havia na grande cidade de Nínive, segundo Jonas 4:11?', 'facil', 'Cerca de doze mil', 'Mais de cento e vinte mil', 'Exatamente quarenta mil', 'Cerca de três mil', 'B', 'Jonas 4:11: "não hei de eu ter compaixão da grande cidade de Nínive, em que há mais de cento e vinte mil pessoas?" É com esse número — e com "muitos animais" — que Deus encerra o livro, defendendo sua misericórdia.', 'Eram mais de cem mil pessoas.', 'texto_biblico', 15),
('00000000-0000-4000-8000-030000000201', 'jonas', 1, 'Como Nínive é chamada em Jonas 1:2?', 'medio', 'Cidade santa', 'Grande cidade', 'Cidade fortificada', 'Cidade dos reis', 'B', 'Jonas 1:2: "vai à grande cidade de Nínive." A expressão "grande cidade" se repete em 3:2-3 e 4:11, ressaltando a importância da missão: Deus se importava até com a capital inimiga.', 'O adjetivo destaca o tamanho e a importância dela.', 'texto_biblico', 16),
('00000000-0000-4000-8000-030000000202', 'jonas', 1, 'Por que Jonas devia clamar contra Nínive?', 'medio', 'Porque a cidade era pobre', 'Porque sua maldade subiu até Deus', 'Porque faltava água lá', 'Porque o rei pedira um profeta', 'B', 'Jonas 1:2: "porque a sua maldade subiu até mim." Nínive, capital da Assíria, era famosa pela crueldade — e Deus, que vê todas as nações, a chamou a contas.', 'O motivo subiu até Deus como um mau cheiro.', 'texto_biblico', 17),
('00000000-0000-4000-8000-030000000203', 'jonas', 1, 'O que os marinheiros fizeram com a carga do navio durante a tempestade?', 'medio', 'Venderam aos passageiros', 'Lançaram ao mar para aliviar o navio', 'Esconderam no porão', 'Ofereceram aos deuses', 'B', 'Jonas 1:5: os marinheiros "lançaram ao mar a carga que estava no navio, para o aliviarem." Mesmo pagãos, agiram com prudência — enquanto o profeta dormia no porão.', 'Eles aliviaram o peso do navio.', 'texto_biblico', 18),
('00000000-0000-4000-8000-030000000204', 'jonas', 1, 'Onde estava Jonas enquanto a tempestade ameaçava o navio?', 'medio', 'Orando no convés', 'Ajudando os marinheiros', 'Dormindo no porão do navio', 'Olhando o horizonte na proa', 'C', 'Jonas 1:5: Jonas "desceu ao porão do navio; deitou-se e dormia profundamente." O contraste é proposital: os pagãos clamavam aos seus deuses, e o profeta do Deus verdadeiro dormia.', 'Ele desceu e dormia profundamente.', 'texto_biblico', 19),
('00000000-0000-4000-8000-030000000205', 'jonas', 1, 'O que o capitão do navio disse a Jonas?', 'medio', '"Paga a tua passagem!"', '"Levanta-te, invoca o teu Deus!"', '"Assume o leme do navio!"', '"Salta do navio agora!"', 'B', 'Jonas 1:6: "Que tens, ó tu que dormes? Levanta-te, invoca o teu Deus! Talvez Deus se lembre de nós, para que não pereçamos." O capitão pagão pregou ao profeta: em crise, clame a Deus.', 'Ele mandou o dorminhoco orar.', 'texto_biblico', 20),
('00000000-0000-4000-8000-030000000206', 'jonas', 1, 'Complete Jonas 1:9: "Eu sou ___, e temo ao Senhor".', 'medio', 'profeta', 'hebreu', 'pescador', 'estrangeiro', 'B', 'Jonas 1:9: "Eu sou hebreu e temo ao Senhor, o Deus do céu, que fez o mar e a terra." "Hebreu" era o nome pelo qual os israelitas se apresentavam aos estrangeiros.', 'É o nome do povo de Israel diante dos estrangeiros.', 'texto_biblico', 21),
('00000000-0000-4000-8000-030000000207', 'jonas', 1, 'Como Jonas descreveu o Deus a quem temia?', 'medio', 'Deus do céu, que fez o mar e a terra', 'Deus dos montes somente', 'Deus dos venezianos', 'Deus que mora no templo', 'A', 'Jonas 1:9: "o Deus do céu, que fez o mar e a terra." A confissão é irônica: Jonas cria num Deus criador do mar — e tentava fugir dele pelo mar.', 'Ele é o Criador de tudo, inclusive do mar revolto.', 'texto_biblico', 22),
('00000000-0000-4000-8000-030000000208', 'jonas', 1, 'Antes de lançar Jonas ao mar, o que os marinheiros tentaram fazer?', 'medio', 'Esperar a tempestade passar', 'Remar para alcançar a terra', 'Oferecer ouro ao mar', 'Voltar para Jope velejando', 'B', 'Jonas 1:13: "os homens remavam, esforçando-se por alcançar a terra, mas não podiam, porque o mar se ia tornando cada vez mais tempestuoso." Os pagãos mostraram mais misericórdia que o profeta mostrara a Nínive.', 'Eles se esforçaram com os remos.', 'texto_biblico', 23),
('00000000-0000-4000-8000-030000000209', 'jonas', 1, 'Depois que o mar se acalmou, o que os marinheiros fizeram?', 'medio', 'Fugiram para Társis', 'Temeram ao Senhor e lhe ofereceram sacrifício e votos', 'Jogaram Jonas de volta ao mar', 'Queimaram o navio em gratidão', 'B', 'Jonas 1:16: "Temeram, pois, estes homens em extremo ao Senhor; ofereceram sacrifícios ao Senhor e fizeram votos." O profeta fujão acabou evangelizando a tripulação: os marinheiros se converteram ao Senhor.', 'Eles se converteram: temeram, sacrificaram e prometeram.', 'texto_biblico', 24),
('00000000-0000-4000-8000-030000000210', 'jonas', 2, 'De onde Jonas orou a oração do capítulo 2?', 'medio', 'Do convés do navio', 'Do ventre do peixe', 'Da praia de Jope', 'Do templo de Jerusalém', 'B', 'Jonas 2:1: "Jonas orou ao Senhor, seu Deus, do ventre do peixe." A oração é um salmo de gratidão cheio de citações dos Salmos — prova de que Jonas conhecia as Escrituras.', 'Foi do lugar mais improvável: dentro do peixe.', 'texto_biblico', 25),
('00000000-0000-4000-8000-030000000211', 'jonas', 2, 'Complete Jonas 2:2: "Na minha ___ clamei ao Senhor, e ele me respondeu".', 'medio', 'alegria', 'angústia', 'velhice', 'festa', 'B', 'Jonas 2:2: "Na minha angústia, clamei ao Senhor, e ele me respondeu; do ventre do abismo, gritei, e tu me ouviste a voz." Deus ouve até no fundo do mar.', 'É o aperto que nos faz clamar.', 'texto_biblico', 26),
('00000000-0000-4000-8000-030000000212', 'jonas', 2, 'Segundo Jonas 2:5, o que se enrolou na cabeça de Jonas?', 'medio', 'Redes de pesca', 'Algas', 'Cordas do navio', 'Cabelos de náufragos', 'B', 'Jonas 2:5: "As águas me cercaram até à alma, o abismo me rodeou; e as algas se enrolaram na minha cabeça." O detalhe mostra que Jonas realmente desceu ao fundo do mar antes de ser tragado.', 'São as plantas do fundo do mar.', 'texto_biblico', 27),
('00000000-0000-4000-8000-030000000213', 'jonas', 2, 'Complete Jonas 2:9: "o que votei ___".', 'medio', 'esquecerei', 'pagarei', 'cantarei', 'esconderei', 'B', 'Jonas 2:9: "o que votei pagarei." No ventre do peixe, Jonas renovou seus votos a Deus — e Deus lhe deu uma segunda chance: o peixe o vomitou em terra (2:10).', 'Voto feito a Deus precisa ser cumprido.', 'texto_biblico', 28),
('00000000-0000-4000-8000-030000000214', 'jonas', 2, 'Como Jonas saiu do ventre do peixe?', 'medio', 'Nadou até a praia', 'O peixe o vomitou na terra', 'Pescadores o resgataram', 'O peixe o levou até Nínive', 'B', 'Jonas 2:10: "Falou, pois, o Senhor ao peixe, e este vomitou a Jonas na terra." Até o peixe obedece à voz do Senhor — contraste com o profeta, que precisou aprender a obedecer.', 'O peixe obedeceu à ordem de Deus.', 'texto_biblico', 29),
('00000000-0000-4000-8000-030000000215', 'jonas', 3, 'Qual era a extensão de Nínive, segundo Jonas 3:3?', 'medio', 'Um dia de caminho', 'Três dias de caminho', 'Sete dias de caminho', 'Uma hora de caminho', 'B', 'Jonas 3:3: "Ora, Nínive era cidade mui grande, de três dias para percorrê-la." A grandeza da cidade realça a grandeza do arrependimento — e Jonas pregou andando apenas um dia (3:4).', 'Era uma cidade de três dias de travessia.', 'texto_biblico', 30),
('00000000-0000-4000-8000-030000000216', 'jonas', 3, 'Quem em Nínive se vestiu de saco, segundo Jonas 3:5?', 'medio', 'Somente os sacerdotes', 'Desde o maior até o menor', 'Somente as mulheres', 'Somente os estrangeiros', 'B', 'Jonas 3:5: vestiram-se de saco "desde o maior até ao menor deles." O arrependimento alcançou todas as classes: do rei (3:6) ao mais humilde — e até os animais (3:7-8).', 'Foi do rei ao mais humilde.', 'texto_biblico', 31),
('00000000-0000-4000-8000-030000000217', 'jonas', 3, 'No decreto do rei de Nínive, quem deveria jejuar e se cobrir de saco?', 'medio', 'Somente os homens livres', 'Homens e animais', 'Somente os soldados', 'Somente os profetas', 'B', 'Jonas 3:7-8: "Nem homens, nem animais, nem bois, nem ovelhas provem coisa alguma... mas sejam cobertos de saco, tanto homens como animais." Até os animais participaram do luto — sinal da seriedade do arrependimento.', 'O decreto alcançou até os bichos.', 'texto_biblico', 32),
('00000000-0000-4000-8000-030000000218', 'jonas', 4, 'Por que Jonas fugiu para Társis, segundo ele mesmo confessa em 4:2?', 'medio', 'Porque tinha medo do mar', 'Porque sabia que Deus é misericordioso e perdoaria Nínive', 'Porque não sabia o caminho', 'Porque estava doente', 'B', 'Jonas 4:2: "sabia que és Deus clemente, e misericordioso, e tardio em irar-se, e grande em benignidade." Jonas fugiu não por medo dos assírios, mas por medo da misericórdia: não queria que Deus perdoasse os inimigos de Israel.', 'Ele conhecia bem o coração perdoador de Deus.', 'texto_biblico', 33),
('00000000-0000-4000-8000-030000000219', 'jonas', 4, 'O que Deus preparou para dar sombra a Jonas a leste de Nínive?', 'medio', 'Uma nuvem', 'Uma planta (aboboreira/ricino)', 'Uma tenda de couro', 'Uma figueira velha', 'B', 'Jonas 4:6: "Deus preparou uma planta (kikayon, traduzida como aboboreira ou rícino), que subiu por cima de Jonas, para que fizesse sombra sobre sua cabeça." Jonas se alegrou muito — preparando a lição final do livro.', 'Foi uma planta que cresceu depressa sobre ele.', 'texto_biblico', 34),
('00000000-0000-4000-8000-030000000220', 'jonas', 4, 'Vendo que Deus perdoara Nínive, como Jonas se sentiu?', 'medio', 'Alegre e grato', 'Desgostoso e irado', 'Indiferente', 'Com medo do rei', 'B', 'Jonas 4:1: "Com isso, desgostou-se Jonas extremamente e ficou irado." O pregador do arrependimento se irou com o sucesso da própria pregação — o coração do livro é essa contradição de Jonas.', 'Ele se irou com a misericórdia de Deus.', 'texto_biblico', 35),
('00000000-0000-4000-8000-030000000301', 'jonas', 1, 'O que Jonas pagou ao embarcar no navio para Társis?', 'dificil', 'Um tributo ao capitão', 'A passagem (o frete)', 'Uma oferta aos deuses', 'O dobro do preço da carga', 'B', 'Jonas 1:3: Jonas "pagou a passagem e embarcou nele." Fugir de Deus sempre tem um preço: Jonas pagou a passagem, perdeu a carga dos outros, quase perdeu a vida — e ainda precisou aprender a lição.', 'Fugir de Deus sempre custa caro: ele pagou para embarcar.', 'texto_biblico', 36),
('00000000-0000-4000-8000-030000000302', 'jonas', 1, 'Sobre quem caiu a sorte lançada pelos marinheiros?', 'dificil', 'Sobre o capitão', 'Sobre Jonas', 'Sobre o passageiro mais rico', 'Sobre ninguém, repetiram o sorteio', 'B', 'Jonas 1:7: "lançaram sortes... e a sorte caiu sobre Jonas." Deus dirigiu o sorteio para expor o profeta fujão — como diz Provérbios 16:33, "a sorte se lança no regaço, mas do Senhor procede toda a decisão."', 'Deus dirigiu o sorteio para expor o culpado.', 'texto_biblico', 37),
('00000000-0000-4000-8000-030000000303', 'jonas', 2, 'Complete Jonas 2:5: "As águas me cercaram até à ___".', 'dificil', 'cintura', 'alma', 'cabeça apenas', 'proa do navio', 'B', 'Jonas 2:5: "As águas me cercaram até à alma, o abismo me rodeou." A linguagem é a dos salmos de aflição (Salmos 69:1): Jonas descreve a morte iminente antes do livramento.', 'As águas chegaram ao mais profundo do seu ser.', 'texto_biblico', 38),
('00000000-0000-4000-8000-030000000304', 'jonas', 2, 'Complete Jonas 2:6: "Desci até aos ___ dos montes".', 'dificil', 'pés', 'fundamentos', 'vales', 'rios', 'B', 'Jonas 2:6: "Desci até aos fundamentos dos montes; a terra encerrou-me para sempre com os seus ferrolhos." Jonas desceu ao mais fundo — e de lá Deus "fez subir da sepultura" a sua vida.', 'É a base mais funda, onde os montes se apoiam.', 'texto_biblico', 39),
('00000000-0000-4000-8000-030000000305', 'jonas', 2, 'Segundo Jonas 2:8, os que se entregam à idolatria vã abandonam…', 'dificil', 'as suas riquezas', 'aquele que lhes é misericordioso', 'os seus amigos', 'a sua terra natal', 'B', 'Jonas 2:8: "Os que se entregam à idolatria vã abandonam aquele que lhes é misericordioso." No fundo do mar, Jonas reconheceu: trocar Deus por ídolos é abandonar a própria misericórdia.', 'Eles abandonam o próprio Deus misericordioso.', 'texto_biblico', 40),
('00000000-0000-4000-8000-030000000306', 'jonas', 3, 'No decreto do rei, o que se esperava que Deus fizesse? "Quem sabe se Deus se ___?"', 'dificil', 'esconderá', 'voltará e se arrependerá', 'calarã para sempre', 'mostrará em sonhos', 'B', 'Jonas 3:9: "Quem sabe se Deus se voltará, e se arrependerá, e se apartará do furor da sua ira, de sorte que não pereçamos?" O rei pagão entendeu o coração de Deus melhor que o profeta: Deus se agrada em perdoar quem se arrepende.', 'O rei esperava que Deus mudasse de propósito.', 'texto_biblico', 41),
('00000000-0000-4000-8000-030000000307', 'jonas', 4, 'Como Deus respondeu à ira de Jonas em 4:4?', 'dificil', '"Cala-te, profeta rebelde!"', '"É razoável essa tua ira?"', '"Volta para Israel agora!"', '"Não te escolhi mais!"', 'B', 'Jonas 4:4: "Respondeu o Senhor: É razoável essa tua ira?" Em vez de repreender com dureza, Deus fez uma pergunta que expõe o absurdo: irar-se porque Deus perdoou é irracional.', 'Deus respondeu com uma pergunta, não com uma repreensão.', 'texto_biblico', 42),
('00000000-0000-4000-8000-030000000308', 'jonas', 4, 'Para que lado da cidade Jonas saiu após pregar?', 'dificil', 'Oeste', 'Norte', 'Oriente (leste)', 'Sul', 'C', 'Jonas 4:5: Jonas "saiu da cidade e assentou-se ao oriente dela." Do alto, a leste, ele assistiria ao que aconteceria com Nínive — ainda esperando o fogo do juízo.', 'É o lado onde o sol nasce.', 'texto_biblico', 43),
('00000000-0000-4000-8000-030000000309', 'jonas', 4, 'O que Jonas construiu a leste de Nínive?', 'dificil', 'Um altar', 'Uma cabana (enramada)', 'Um muro', 'Uma torre de vigia', 'B', 'Jonas 4:5: Jonas "fez ali uma cabana (enramada) e assentou-se debaixo dela, à sombra, até ver o que aconteceria à cidade." A cabana de folhas seria completada pela sombra da planta de Deus (4:6).', 'Era um abrigo de folhas para fazer sombra.', 'texto_biblico', 44),
('00000000-0000-4000-8000-030000000310', 'jonas', 4, 'O que Deus preparou para ferir a planta que dava sombra a Jonas?', 'dificil', 'Um verme', 'Uma tempestade', 'Uma nuvem de gafanhotos', 'Um raio', 'A', 'Jonas 4:7: "Deus preparou um verme, ao subir da alva do dia seguinte, o qual feriu a planta, e esta se secou." O mesmo Deus que preparou o peixe (1:17) e a planta (4:6) preparou o verme e o vento (4:8): tudo O serve.', 'Foi um bichinho pequeno, ao amanhecer.', 'texto_biblico', 45),
('00000000-0000-4000-8000-030000000311', 'jonas', 4, 'Que vento Deus preparou contra Jonas, segundo 4:8?', 'dificil', 'Um vento do norte, frio', 'Um vento oriental calmoso (veemente)', 'Uma brisa suave do mar', 'Um redemoinho do deserto', 'B', 'Jonas 4:8: "Deus preparou um vento calmoso, oriental." O vento quente do leste, somado ao sol sobre a cabeça, fez Jonas desmaiar e pedir a morte — preparando a pergunta final de Deus.', 'Era um vento quente vindo do leste.', 'texto_biblico', 46),
('00000000-0000-4000-8000-030000000312', 'jonas', 4, 'Complete o lamento de Jonas em 4:8: "Melhor me é ___ do que viver".', 'dificil', 'dormir', 'morrer', 'calar', 'fugir', 'B', 'Jonas 4:8: "melhor me é morrer do que viver." Jonas repetiu o pedido de 4:3: preferia morrer a ver Nínive perdoada — e agora, sem a sombra da planta. A resposta de Deus veio em forma de lição (4:10-11).', 'Ele repetiu o pedido que já fizera no versículo 3.', 'texto_biblico', 47),
('00000000-0000-4000-8000-030000000313', 'jonas', 4, 'Segundo Jonas 4:11, os ninivitas não sabiam discernir entre…', 'dificil', 'o bem e o mal', 'a mão direita e a esquerda', 'o dia e a noite', 'a verdade e a mentira', 'B', 'Jonas 4:11: "mais de cento e vinte mil pessoas, que não sabem discernir entre a mão direita e a esquerda." A expressão indica ignorância espiritual (como crianças pequenas): motivo para compaixão, não para ira.', 'É algo que até uma criança pequena confunde.', 'texto_biblico', 48),
('00000000-0000-4000-8000-030000000314', 'jonas', 4, 'Além das cento e vinte mil pessoas, de quem mais Deus disse ter compaixão em 4:11?', 'dificil', 'Dos reis vizinhos', 'De muitos animais', 'Dos exilados de Israel', 'Dos marinheiros do navio', 'B', 'Jonas 4:11 termina: "e também muitos animais?" O livro se encerra com uma pergunta sem resposta registrada — e com Deus defendendo sua compaixão até pelos animais da cidade inimiga.', 'O livro termina falando deles, com uma pergunta.', 'texto_biblico', 49),
('00000000-0000-4000-8000-030000000315', 'jonas', 4, 'Complete Jonas 4:10: "Tiveste compaixão da planta, na qual não ___".', 'dificil', 'trabalhaste', 'confiaste', 'descansaste', 'meditaste', 'A', 'Jonas 4:10: "Tiveste compaixão da planta, na qual não trabalhaste, nem a fizeste crescer; que numa noite nasceu e numa noite pereceu." O argumento é do menor para o maior: se Jonas amou a planta passageira, quanto mais Deus amaria Nínive.', 'Jonas não fez nada para merecer a planta.', 'texto_biblico', 50)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- CONQUISTAS
-- ---------------------------------------------------------------------------
insert into public.achievements (id, code, book_id, name, description, icon, criteria) values
  ('22222222-2222-4222-8222-222222220101', 'OSEIAS_FIRST_GAME', 'oseias', 'Primeira Partida — Oséias', 'Complete a sua primeira partida no Quiz de Oséias.', '🎯', '{"type":"attempts_count","value":1}'::jsonb),
  ('22222222-2222-4222-8222-222222220102', 'OSEIAS_FIVE_GAMES', 'oseias', '5 Partidas — Oséias', 'Complete 5 partidas no Quiz de Oséias.', '🔥', '{"type":"attempts_count","value":5}'::jsonb),
  ('22222222-2222-4222-8222-222222220103', 'OSEIAS_TEN_GAMES', 'oseias', '10 Partidas — Oséias', 'Complete 10 partidas no Quiz de Oséias.', '⚡', '{"type":"attempts_count","value":10}'::jsonb),
  ('22222222-2222-4222-8222-222222220104', 'OSEIAS_PERFECT_SCORE', 'oseias', '100% de Acertos — Oséias', 'Termine uma partida de Oséias com todas as respostas corretas.', '💯', '{"type":"perfect_attempt","value":true}'::jsonb),
  ('22222222-2222-4222-8222-222222220105', 'OSEIAS_TOP_TEN', 'oseias', 'Top 10 — Oséias', 'Entre no top 10 do ranking de Oséias.', '🏅', '{"type":"leaderboard_position","value":10}'::jsonb),
  ('22222222-2222-4222-8222-222222220106', 'OSEIAS_FIRST_PLACE', 'oseias', '1º Lugar — Oséias', 'Alcance o 1º lugar do ranking de Oséias.', '👑', '{"type":"leaderboard_position","value":1}'::jsonb),
  ('22222222-2222-4222-8222-222222220107', 'OSEIAS_EXPERT', 'oseias', 'Especialista em Oséias', 'Acumule 100 respostas corretas em Oséias com 85% ou mais de acerto.', '📖', '{"type":"expert","correct":100,"min_accuracy":85}'::jsonb),
  ('22222222-2222-4222-8222-222222220201', 'OBADIAS_FIRST_GAME', 'obadias', 'Primeira Partida — Obadias', 'Complete a sua primeira partida no Quiz de Obadias.', '🎯', '{"type":"attempts_count","value":1}'::jsonb),
  ('22222222-2222-4222-8222-222222220202', 'OBADIAS_FIVE_GAMES', 'obadias', '5 Partidas — Obadias', 'Complete 5 partidas no Quiz de Obadias.', '🔥', '{"type":"attempts_count","value":5}'::jsonb),
  ('22222222-2222-4222-8222-222222220203', 'OBADIAS_TEN_GAMES', 'obadias', '10 Partidas — Obadias', 'Complete 10 partidas no Quiz de Obadias.', '⚡', '{"type":"attempts_count","value":10}'::jsonb),
  ('22222222-2222-4222-8222-222222220204', 'OBADIAS_PERFECT_SCORE', 'obadias', '100% de Acertos — Obadias', 'Termine uma partida de Obadias com todas as respostas corretas.', '💯', '{"type":"perfect_attempt","value":true}'::jsonb),
  ('22222222-2222-4222-8222-222222220205', 'OBADIAS_TOP_TEN', 'obadias', 'Top 10 — Obadias', 'Entre no top 10 do ranking de Obadias.', '🏅', '{"type":"leaderboard_position","value":10}'::jsonb),
  ('22222222-2222-4222-8222-222222220206', 'OBADIAS_FIRST_PLACE', 'obadias', '1º Lugar — Obadias', 'Alcance o 1º lugar do ranking de Obadias.', '👑', '{"type":"leaderboard_position","value":1}'::jsonb),
  ('22222222-2222-4222-8222-222222220207', 'OBADIAS_EXPERT', 'obadias', 'Especialista em Obadias', 'Acumule 100 respostas corretas em Obadias com 85% ou mais de acerto.', '📖', '{"type":"expert","correct":100,"min_accuracy":85}'::jsonb),
  ('22222222-2222-4222-8222-222222220301', 'JONAS_FIRST_GAME', 'jonas', 'Primeira Partida — Jonas', 'Complete a sua primeira partida no Quiz de Jonas.', '🎯', '{"type":"attempts_count","value":1}'::jsonb),
  ('22222222-2222-4222-8222-222222220302', 'JONAS_FIVE_GAMES', 'jonas', '5 Partidas — Jonas', 'Complete 5 partidas no Quiz de Jonas.', '🔥', '{"type":"attempts_count","value":5}'::jsonb),
  ('22222222-2222-4222-8222-222222220303', 'JONAS_TEN_GAMES', 'jonas', '10 Partidas — Jonas', 'Complete 10 partidas no Quiz de Jonas.', '⚡', '{"type":"attempts_count","value":10}'::jsonb),
  ('22222222-2222-4222-8222-222222220304', 'JONAS_PERFECT_SCORE', 'jonas', '100% de Acertos — Jonas', 'Termine uma partida de Jonas com todas as respostas corretas.', '💯', '{"type":"perfect_attempt","value":true}'::jsonb),
  ('22222222-2222-4222-8222-222222220305', 'JONAS_TOP_TEN', 'jonas', 'Top 10 — Jonas', 'Entre no top 10 do ranking de Jonas.', '🏅', '{"type":"leaderboard_position","value":10}'::jsonb),
  ('22222222-2222-4222-8222-222222220306', 'JONAS_FIRST_PLACE', 'jonas', '1º Lugar — Jonas', 'Alcance o 1º lugar do ranking de Jonas.', '👑', '{"type":"leaderboard_position","value":1}'::jsonb),
  ('22222222-2222-4222-8222-222222220307', 'JONAS_EXPERT', 'jonas', 'Especialista em Jonas', 'Acumule 100 respostas corretas em Jonas com 85% ou mais de acerto.', '📖', '{"type":"expert","correct":100,"min_accuracy":85}'::jsonb)
on conflict (code) do nothing;

-- ---------------------------------------------------------------------------
-- CONFERÊNCIA
-- ---------------------------------------------------------------------------
select b.id as livro, b.name,
  count(*) filter (where q.difficulty = 'facil')   as faceis,
  count(*) filter (where q.difficulty = 'medio')   as medias,
  count(*) filter (where q.difficulty = 'dificil') as dificeis,
  count(*) as total
from public.books b join public.questions q on q.book_id = b.id
where b.active and q.active group by b.id, b.name order by b.order_index;
